sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kingsonnwoke/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kingsonnwoke/docker-react npm run test
